music.setBuiltInSpeakerEnabled(true)
music.setVolume(255)
music.setTempo(106)
music.playTone(277, music.beat(BeatFraction.Whole))
music.playTone(370, music.beat(BeatFraction.Whole))
music.playTone(330, music.beat(BeatFraction.Half))
music.playTone(370, music.beat(BeatFraction.Half))
music.playTone(294, music.beat(BeatFraction.Whole))
music.playTone(277, music.beat(BeatFraction.Whole))
basic.pause(1)
music.playTone(247, music.beat(BeatFraction.Half))
music.playTone(277, music.beat(BeatFraction.Half))
music.playTone(220, music.beat(BeatFraction.Whole))
music.playTone(247, music.beat(BeatFraction.Half))
music.playTone(262, music.beat(BeatFraction.Half))
music.playTone(277, music.beat(BeatFraction.Whole))
music.playTone(220, music.beat(BeatFraction.Whole))
music.playTone(208, music.beat(BeatFraction.Half))
music.playTone(220, music.beat(BeatFraction.Half))
music.playTone(247, music.beat(BeatFraction.Half))
basic.pause(1)
music.playTone(277, music.beat(BeatFraction.Half))
music.playTone(294, music.beat(BeatFraction.Whole))
music.playTone(294, music.beat(BeatFraction.Half))
music.playTone(330, music.beat(BeatFraction.Half))
music.playTone(294, music.beat(BeatFraction.Whole))
music.playTone(277, music.beat(BeatFraction.Whole))
music.playTone(277, music.beat(BeatFraction.Whole))
music.playTone(370, music.beat(BeatFraction.Whole))
basic.pause(1)
music.playTone(330, music.beat(BeatFraction.Half))
music.playTone(370, music.beat(BeatFraction.Half))
music.playTone(294, music.beat(BeatFraction.Whole))
music.playTone(277, music.beat(BeatFraction.Whole))
music.playTone(247, music.beat(BeatFraction.Half))
music.playTone(277, music.beat(BeatFraction.Half))
music.playTone(220, music.beat(BeatFraction.Whole))
music.playTone(247, music.beat(BeatFraction.Half))
music.playTone(262, music.beat(BeatFraction.Half))
music.playTone(277, music.beat(BeatFraction.Whole))
basic.pause(1)
music.playTone(220, music.beat(BeatFraction.Whole))
music.playTone(208, music.beat(BeatFraction.Half))
music.playTone(220, music.beat(BeatFraction.Half))
music.playTone(247, music.beat(BeatFraction.Half))
music.playTone(277, music.beat(BeatFraction.Half))
music.playTone(294, music.beat(BeatFraction.Whole))
music.playTone(294, music.beat(BeatFraction.Half))
music.playTone(330, music.beat(BeatFraction.Half))
music.playTone(294, music.beat(BeatFraction.Whole))
music.playTone(277, music.beat(BeatFraction.Whole))
basic.forever(function () {
	
})
